spring.application.name=hex_assesssment

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=5170

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true